package y.b;

public interface ITVisitor
{
    public long tRun(long tVisitorN, long tElementN, long a, long b, long c, long d, long e);

    public long visit(TAlpha00 element, long a, long b, long c, long d, long e);
    public long visit(TBeta00 element, long a, long b, long c, long d, long e);
    public long visit(TGamma00 element, long a, long b, long c, long d, long e);
    public long visit(TDelta00 element, long a, long b, long c, long d, long e);
    public long visit(TEpsilon00 element, long a, long b, long c, long d, long e);
    public long visit(TDzeta00 element, long a, long b, long c, long d, long e);
    public long visit(TEta00 element, long a, long b, long c, long d, long e);
    public long visit(TTheta00 element, long a, long b, long c, long d, long e);
    public long visit(TIota00 element, long a, long b, long c, long d, long e);
    public long visit(TKappa00 element, long a, long b, long c, long d, long e);
    public long visit(TLambda00 element, long a, long b, long c, long d, long e);
    public long visit(TMu00 element, long a, long b, long c, long d, long e);
    public long visit(TNu00 element, long a, long b, long c, long d, long e);
    public long visit(TXi00 element, long a, long b, long c, long d, long e);
    public long visit(TOmicron00 element, long a, long b, long c, long d, long e);
    public long visit(TPi00 element, long a, long b, long c, long d, long e);
    public long visit(TRho00 element, long a, long b, long c, long d, long e);
    public long visit(TSigma00 element, long a, long b, long c, long d, long e);
    public long visit(TTau00 element, long a, long b, long c, long d, long e);
    public long visit(TUpsilon00 element, long a, long b, long c, long d, long e);
    public long visit(TPhi00 element, long a, long b, long c, long d, long e);
    public long visit(TKhi00 element, long a, long b, long c, long d, long e);
    public long visit(TPsi00 element, long a, long b, long c, long d, long e);
    public long visit(TOmega00 element, long a, long b, long c, long d, long e);

    public long visit(TAlpha01 element, long a, long b, long c, long d, long e);
    public long visit(TBeta01 element, long a, long b, long c, long d, long e);
    public long visit(TGamma01 element, long a, long b, long c, long d, long e);
    public long visit(TDelta01 element, long a, long b, long c, long d, long e);
    public long visit(TEpsilon01 element, long a, long b, long c, long d, long e);
    public long visit(TDzeta01 element, long a, long b, long c, long d, long e);
    public long visit(TEta01 element, long a, long b, long c, long d, long e);
    public long visit(TTheta01 element, long a, long b, long c, long d, long e);
    public long visit(TIota01 element, long a, long b, long c, long d, long e);
    public long visit(TKappa01 element, long a, long b, long c, long d, long e);
    public long visit(TLambda01 element, long a, long b, long c, long d, long e);
    public long visit(TMu01 element, long a, long b, long c, long d, long e);
    public long visit(TNu01 element, long a, long b, long c, long d, long e);
    public long visit(TXi01 element, long a, long b, long c, long d, long e);
    public long visit(TOmicron01 element, long a, long b, long c, long d, long e);
    public long visit(TPi01 element, long a, long b, long c, long d, long e);
    public long visit(TRho01 element, long a, long b, long c, long d, long e);
    public long visit(TSigma01 element, long a, long b, long c, long d, long e);
    public long visit(TTau01 element, long a, long b, long c, long d, long e);
    public long visit(TUpsilon01 element, long a, long b, long c, long d, long e);
    public long visit(TPhi01 element, long a, long b, long c, long d, long e);
    public long visit(TKhi01 element, long a, long b, long c, long d, long e);
    public long visit(TPsi01 element, long a, long b, long c, long d, long e);
    public long visit(TOmega01 element, long a, long b, long c, long d, long e);

    public long visit(TAlpha02 element, long a, long b, long c, long d, long e);
    public long visit(TBeta02 element, long a, long b, long c, long d, long e);
    public long visit(TGamma02 element, long a, long b, long c, long d, long e);
    public long visit(TDelta02 element, long a, long b, long c, long d, long e);
    public long visit(TEpsilon02 element, long a, long b, long c, long d, long e);
    public long visit(TDzeta02 element, long a, long b, long c, long d, long e);
    public long visit(TEta02 element, long a, long b, long c, long d, long e);
    public long visit(TTheta02 element, long a, long b, long c, long d, long e);
    public long visit(TIota02 element, long a, long b, long c, long d, long e);
    public long visit(TKappa02 element, long a, long b, long c, long d, long e);
    public long visit(TLambda02 element, long a, long b, long c, long d, long e);
    public long visit(TMu02 element, long a, long b, long c, long d, long e);
    public long visit(TNu02 element, long a, long b, long c, long d, long e);
    public long visit(TXi02 element, long a, long b, long c, long d, long e);
    public long visit(TOmicron02 element, long a, long b, long c, long d, long e);
    public long visit(TPi02 element, long a, long b, long c, long d, long e);
    public long visit(TRho02 element, long a, long b, long c, long d, long e);
    public long visit(TSigma02 element, long a, long b, long c, long d, long e);
    public long visit(TTau02 element, long a, long b, long c, long d, long e);
    public long visit(TUpsilon02 element, long a, long b, long c, long d, long e);
    public long visit(TPhi02 element, long a, long b, long c, long d, long e);
    public long visit(TKhi02 element, long a, long b, long c, long d, long e);
    public long visit(TPsi02 element, long a, long b, long c, long d, long e);
    public long visit(TOmega02 element, long a, long b, long c, long d, long e);

    public long visit(TAlpha03 element, long a, long b, long c, long d, long e);
    public long visit(TBeta03 element, long a, long b, long c, long d, long e);
    public long visit(TGamma03 element, long a, long b, long c, long d, long e);
    public long visit(TDelta03 element, long a, long b, long c, long d, long e);
    public long visit(TEpsilon03 element, long a, long b, long c, long d, long e);
    public long visit(TDzeta03 element, long a, long b, long c, long d, long e);
    public long visit(TEta03 element, long a, long b, long c, long d, long e);
    public long visit(TTheta03 element, long a, long b, long c, long d, long e);
    public long visit(TIota03 element, long a, long b, long c, long d, long e);
    public long visit(TKappa03 element, long a, long b, long c, long d, long e);
    public long visit(TLambda03 element, long a, long b, long c, long d, long e);
    public long visit(TMu03 element, long a, long b, long c, long d, long e);
    public long visit(TNu03 element, long a, long b, long c, long d, long e);
    public long visit(TXi03 element, long a, long b, long c, long d, long e);
    public long visit(TOmicron03 element, long a, long b, long c, long d, long e);
    public long visit(TPi03 element, long a, long b, long c, long d, long e);
    public long visit(TRho03 element, long a, long b, long c, long d, long e);
    public long visit(TSigma03 element, long a, long b, long c, long d, long e);
    public long visit(TTau03 element, long a, long b, long c, long d, long e);
    public long visit(TUpsilon03 element, long a, long b, long c, long d, long e);
    public long visit(TPhi03 element, long a, long b, long c, long d, long e);
    public long visit(TKhi03 element, long a, long b, long c, long d, long e);
    public long visit(TPsi03 element, long a, long b, long c, long d, long e);
    public long visit(TOmega03 element, long a, long b, long c, long d, long e);

}
